export const data = [
  {
    id: 1,
    img: "https://res.cloudinary.com/dlqpq9wxh/image/upload/v1645698337/Jisooworld/Screencard/Kid%20jisoo.jpg",
    title: "The day she was born",
    content:
      "Kim Ji-soo 김지수 was born on January 3, 1995 in Gunpo, Gyeonggi Province, South Korea.She has an older brother and sister.As a child, she played basketball and practiced Taekwondo.She was a fan of the Korean boy group TVXQ.Jisoo attended high school at the School of Performing Arts Seoul; in 11th grade, she founded a drama club at the school and earned more experience in the entertainment industry by attending auditions.",
    modal: `Early life
    Kim Ji-soo was born on January 3, 1995 in Gunpo, Gyeonggi Province, South Korea.She has an older brother and sister.As a child, she played basketball and practiced Taekwondo.She was a fan of the Korean boy group TVXQ.Jisoo attended high school at the School of Performing Arts Seoul;in 11th grade, she founded a drama club at the school and earned more experience in the entertainment industry by attending auditions.
    
    2011–2016: Career beginnings and debut with Blackpink
    Main article: Blackpink
    In 2011, Jisoo joined YG Entertainment as a trainee after passing its auditions.In October 2014, she appeared in Epik High's music video for "SPOILER + HAPPEN ENDING" as a heartbroken girl.The same year, she starred in Hi Suhyun's music video for "I'm Different"as Bobby's girlfriend. In 2015, Jisoo made a cameo appearance in the KBS2 drama The Producers with labelmates Sandara Park of 2NE1 and Kang Seung-yoon of Winner.`,
  },
  {
    id: 2,
    img: "https://res.cloudinary.com/dlqpq9wxh/image/upload/v1645698742/Jisooworld/Screencard/jisoo.jpg",
    title: "The day you know her as Jisoo",
    content:
      "Jisoo debuted as one of the oldest of the four members of girl group Blackpink on August 8, 2016, alongside Jennie, Rosé and Lisa, with the release of their single album Square One.",
    modal: `From 2017 to 2018, Jisoo joined Inkigayo as a host alongside Got7's Jin-young and NCT's Doyoung.She first ventured into acting in 2019 with a short cameo appearance in the tvN fantasy drama Arthdal Chronicles.In 2020, Jisoo co-wrote the lead single "Lovesick Girls" of Blackpink's first Korean-language studio album The Album.

    On August 18, 2020 YG Entertainment confirmed Jisoo would star in her first role as a lead actress in the JTBC drama Snowdrop alongside actor Jung Hae-in.The series aired from December 18, 2021, to January 30, 2022, on JTBC domestically and on Disney+ internationally. Despite the controversies related to the alleged historical distortions by the show, Jisoo's acting was positively received by critics, who stated that she "certainly proves her mettle" and that her "range is commendable".YG Entertainment confirmed that Jisoo's debut as a solo artist was in the works but without a date yet due to her commitments to filming Snowdrop. She will be the last member of the Blackpink to make her solo debut.`,
  },
  {
    id: 3,
    img: "https://res.cloudinary.com/dlqpq9wxh/image/upload/v1645698864/Jisooworld/Screencard/Worldtour.jpg",
    title: "In Your Area World Tour",
    content:
      "The In Your Area World Tour (also known as Blackpink World Tour [In Your Area]) was the first worldwide concert tour and the second overall by South Korean girl group Blackpink. The tour began on November 10, 2018 in Seoul, South Korea and ended on February 22, 2020, in Fukuoka, Japan, in support of their albums Square Up (2018) and Kill This Love (2019). It visited a total of 18 countries and 26 cities around the world. The tour is the highest-grossing tour by a Korean girl group.",
    modal: `The concert began with a montage of a rubic cube spelling out "Blackpink" and the names of the group's members on the main stage's screen. The cube then turned into an explosion of pink glitter and rising smokes as all members of Blackpink started rising to the stage and performing "Ddu-Du Ddu-Du" in light pink outfits. The quartet was then lifted on stage platforms to perform "Forever Young" with an outer space-like backdrop on screen.After performing the two verses and the second chorus on the main stage, Blackpink was raised on the platforms again and joined by backup dancers as they sang the final part of the song. The group then greeted and introduced themselves to the audience after the platforms were lowered back to the main stage surface level. Afterward, Blackpink performed "Stay" on chairs on the main stage and walked to the B-stage during the final chorus. The group proceeded to sing "Whistle" on the B-stage for a majority of the song before being accompanied by backup dancers and returning to the main stage for the ending part. The group was then lowered down below the stage by lifts for a costume change to prepare for their respective solo stages.

    Depending on the tour leg, the order of the solo performances changes. In the first Asian leg, Jisoo would commence the portion by coming out on a platform made of disco balls to sing a cover of "Clarity" by Zedd. Her stage would be followed by Lisa dancing to a medley of songs, both solo and with a group of backup dancers. In Seoul, Lisa danced to "I Like It", "Faded" (by Tink) and "Attention"; the dance number was changed to "Take Me" and "Swalla" from the Bangkok date on January 11, 2019 onwards. Subsequently, after Lisa, Rosé rose to the stage along with Dante Jackson from The Band Six on the piano and sang a cover medley of "Let It Be" by the Beatles, "You and I" by former label mate Park Bom and "Only Look At Me" by Taeyang.From April 17, 2019 to the rest of the tour, Rosé opened the solo stages instead of Jisoo. The solo stage portion then concluded with Jennie performing "Solo" with multiple backup dancers whilst a dance hall setting was on display on the screen.The Band Six played an interlude after Jennie went backstage for her costume change.With an exception to Jennie's performance, the solo segment was revamped for the final leg in Japan. Rosé sang a cover of Lewis Capaldi's "Someone You Loved", Lisa's dance number was changed to a medley of "Good Thing" and "Señorita" while Jisoo performed a cover of AKMU's "How Can I Love the Heartbreak, You're the One I Love".
    
    After the release of "Kill This Love" EP in April 2019, Blackpink opened Act III of the concert with "Kill This Love", dressed in street style outfits.The main screen featured different scenes from the song's official music video, served as the performance backdrop. A group of backup dancers joined Blackpink for the ending beat drop of the song in marching band outfits before leaving the stage for the quartet to perform "Don't Know What To Do" on their own. The group spent some time afterward to talk and interact with the audience. Next, "Kiss and Make Up" was performed with each member standing on their respective raised and moving platform while the screen was showing tropical patterns and imagery. The Band Six and backup dancers later returned to the main stage to accompany Blackpink, now back down on stage level, performing "Really" and "See U Later". They all exited the stage when a video interlude featuring Blackpink racing and drifting in Kia motorcars started playing on the screens.
    
    Blackpink, in sparkly costumes, returned to the stage from below and performed "Playing with Fire" to a gate-like setting on the screen. The background changed to kaleidoscope-like graphics when the group sang "Kick It". They moved to the B-stage and proceeded to perform the final two songs "Boombayah" and "As If It's Your Last" there, after a small talk with the audience.
    
    For the encore, the group reappeared on stage in more casual and sporty clothes to perform a remix version of "Ddu-Du Ddu-Du". Following that performance, Blackpink introduced members of the band and the backup dancer group to the audience and thanked them before casually enjoying an instrumental performance of The Band Six themselves. Only the group remained on stage afterward to sing the final song "Hope Not"; they said goodbye to the audience before exiting the stage on a lift lowering them back down to the pit.`,
  },
  {
    id: 4,
    img: "https://res.cloudinary.com/dlqpq9wxh/image/upload/v1645699315/Jisooworld/Screencard/Diormuse.jpg",
    title: "MUSE",
    content: `In December 2019, Jisoo became a local ambassador for Dior's cosmetics brand, Dior Beauty.`,
    modal: `In December 2019, Jisoo became a local ambassador for Dior's cosmetics brand, Dior Beauty.The next summer, Jisoo was recruited to be Dior's muse and modelled for Dior's Fall/Winter 2020 collection. In September 2020, Jisoo covered the 155th edition 2020 of Dazed Korea, where she discussed her work with Dior. She was also appointed as the main model for Cartier's "Pasha de Cartier".In December 2020, Jisoo was photographed with the Lady Dior and D'Lite bags in Dior's Cruise 2020–2021 Collection.

    In January 2021, Dior Beauty's "Dior Forever Skin Glow Cushion", endorsed by Jisoo, was released exclusively in Korea.She also promoted the brand's Spring/Summer Collection, wearing Dior's Caro bag.The next March, Jisoo cemented her long-term partnership with Dior when they announced her as their new global ambassador,alongside Natalie Portman and Cara Delevingne.In May 2021, Jisoo embarked on her first collaboration project with the brand, fronting the Dior Fall '21 and Dior Vespa campaigns as Elle magazine's June cover star, which hit shelves in four countries—Hong Kong, Thailand, Singapore and India.Jisoo modeled Dior's newly launched lip balm, Dior Addict Lip Glow, for the Dior Beauty series.In June 2021, Jisoo attended the Dior Resort 2022 show at Greece's Panathenaic Stadium,wearing all-white linen dress by creative director Maria Grazia Chiuri.In September 2021, Jisoo attended Dior's Womenswear Spring/Summer 2022 show, held during the 2021 Paris Fashion Week at Jardin des Tuileries. She sat in the front row, next to the chairman and CEO of Dior, Pietro Beccari.Ahead of the show, her journey to Paris was documented on Dior's social media accounts, showcasing moments ranging from her visit to the house's ateliers and the inspiration behind the Spring/Summer 2022 collection and to the archives of Lady Dior, named after Princess Diana.`,
  },
  {
    id: 5,
    img: "https://res.cloudinary.com/dlqpq9wxh/image/upload/v1645699571/Jisooworld/Screencard/theshow.jpg",
    title: "Blackpink : The Show",
    content:
      "The Show, officially titled YG Palm Stage ― 2021 Blackpink: The Show,was the first online concert by South Korean girl group Blackpink.",
    modal: `South Korean girl group Blackpink released their first Korean-language studio album, The Album, on October 2, 2020. It received generally favourable reviews from music critics,and was one of the world's best-selling album of 2020.To celebrate the album's release, Blackpink announced their first online pay-per-view concert, The Show, for December 27, 2020. Due to COVID-19 pandemic regulations in South Korea at that time, the concert was postponed to January 31, 2021.Under a partnership between the group's label YG Entertainment and YouTube Music, it was the first concert in YG Entertainment's online concert series "YG Palm Stage". A promotional teaser for the concert was first released on November 23, 2020.It was available exclusively on Blackpink's YouTube channel and included first-time performances of songs from The Album.The Show opened with "Kill This Love", following a video featuring sights of dark and empty cities around the world.Apart of live performances it also included several pre-recorded tracks.Each member performed their own solo stage; Jennie performed her song "Solo" with new rap lyrics written by her, and Rosé shared a preview of her solo debut "Gone", while Jisoo and Lisa performed covers of Tove Lo's "Habits (Stay High)" and Doja Cat's "Say So" respectively.The concert ended with an encore featuring performance of "Forever Young" in which the stage was filled with messages from Blinks (Blackpink's fandom name).`,
  },
  {
    id: 6,
    img: "https://res.cloudinary.com/dlqpq9wxh/image/upload/v1645700011/Jisooworld/Screencard/r3d3b69amjLG92hgu0P-o_qkdj22.jpg",
    title: "Actress Jisoo",
    content:
      "Snowdrop (Korean: 설강화; Hanja: 雪降花; RR: Seolganghwa) is a South Korean television series starring Jung Hae-in, Jisoo, Yoo In-na, Jang Seung-jo, Yoon Se-ah, Kim Hye-yoon, and Jung Yoo-jin. It aired on JTBC from December 18, 2021, to January 30, 2022, every Saturday and Sunday at 22:30 (KST) for 16 episodes. It is also available for streaming on Disney+ in the US and under the Star hub in selected international regions.",
    modal: `Snowdrop takes place in 1987, a pivotal year in South Korean history that included the June 1987 Democracy Movement, a mass protest movement with the purpose of forcing the dictatorship in South Korea to hold fair elections, and the resulting December 1987 democratic elections, which led to the end of the authoritarian Fifth Republic of Korea and the establishment of the democratic Sixth Republic of Korea.

    Snowdrop is set in November and December 1987. Lim Soo-ho (Jung Hae-in) plays a graduate student who is discovered covered in blood by Eun Yeong-ro (Jisoo), a female university student and hides him from the government in her dorm room at her women's university. However, it is revealed that Soo-ho is not who he appears to be. Against the backdrop of political upheaval, the pair's story unfolds and the two develop a romantic relationship.Jung Hae-in as Lim Soo-ho (27 years old),formerly named Lee Tae-san, alias Lim Soo-hyeok. He is a North Korean agent with a mission assigned in South Korea. He lives as a graduate student preparing for a master's thesis in the Department of Economics from the University of Berlin.
    Jisoo as Eun Yeong-ro (20 years old), a freshman at Hosu Women's University in the English Literature Department, who falls in love with Soo-ho at first sight.`,
  },
];
